### PR TITLE
c3p0 to HikariCP. Needs extensive testing.

### PR DESCRIPTION
**Pull request by Elfocrash**

### CODE REVIEW

**Comment by Tayran** [comment]
@Elfocrash I'm going to test this when solving critical problems that are in the project, did you test the basics of the database that work with HikariCP?

**Comment by Elfocrash** [comment]
@Tayran I did and it seems to be working. 
However it still needs to be tested under load.

**Comment by LeonanCarvalho** [comment]
There is no reason to not work since it was modified at the core.
We should expect a more stable behavior of database connections. 
Based on this document https://github.com/brettwooldridge/HikariCP/wiki/Pool-Analysis I can conclude the HikariCP have a good stability and more [performance ](https://raw.githubusercontent.com/wiki/brettwooldridge/HikariCP/Benchmarks.png)

I just concern about logging to debug errors https://github.com/brettwooldridge/HikariCP/wiki/JDBC-Logging#mysql-connectorj

@Elfocrash  Did you know if this version of HikariCP has full support with MySQL 5.7?

I think we will need a test server to deploy it at l2jbrasil.com to make calls and people to play it.

**Comment by Elfocrash** [comment]
@LeonanCarvalho I think what we really need to establish is the default configuration for it.
I set it to what i think would be a good start but you can also read the details about configuration on HikariCP repo itself here https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby

A good example would be to test what the gameserver load speed is with c3p0 and then with HikariCP.

About your MySQL 5.7 i would say that this should not be an issue at all. However have you considered using MariaDB instead of MySQL?
It is compatible with all the connectors and queries of MySQL (as it is a fork of it after all made by the original MySQL creators) but better in many things like development, performance and migration.

**Comment by LeonanCarvalho** [comment]
I have bad experiences with MariaDB, so I have used Oracle MySQL 5.7 community for my devs. 
But we will keep supporting both. 

We are looking for someone to test this changes.

I just changed the base to develop instead master.

**Comment by Elfocrash** [comment]
Then merge it to develop and test it. Develop is meant to be unstable and experimental.

**Comment by Elfocrash** [comment]
I merged in develop in order to test it properly.
Se need to add in readme that develop is unstable experimental branch and people should use master

**Pull request merged**
